### ISSUE TITLE
When installed on the tableau server linux, it does not find CA certificates 

### ISSUE THREAD

**Issue by nevgin** [Altinity/clickhouse-tableau-connector-odbc#11]
OS: Centos 7
When installed on the tableau server, it does not find CA certificates. 
On the Centos 7 system, the default location for CA certificates is /etc/pki/tls/cert.pem however the connector is hardcoded to /usr/local/etc/openssl@1.1/
I ask you to put the parameter into the web form.

**Comment by dima-altinity** [comment]
not sure if parameter in web form will affect settings for connector that is installed on Server.
Soon connector will be published in Tableau Gallery as TACO package.
I'll try to install it and check if it works.
For now you could you simple workaround - create symlink from /usr/local/etc/openssl@1.1/  to your location.
https://www.cyberciti.biz/faq/creating-soft-link-or-symbolic-link/

**Comment by dima-altinity** [comment]
Today connector was published in Tableau Gallery with a lot of fixes.
Path to SSL cert should be configured in ODBC driver settings
