### ISSUE TITLE
BUG working with time

### ISSUE THREAD

**Issue by theSaintBelial** [Altinity/clickhouse-tableau-connector-odbc#12]
Display only 00:00:00 value of the whole day when time filter is from 00:00:00 to hh:mm:ss.

For example, making easy line chart from next data:

just time - toDateTime64(0) with 1 min time accuracy
just price - Float64 value

If i'm trying to make such a line chart with "just time" filter like above, I get only 1 value at the 00:00:00. But I have all the data to 15:15.
![image](https://user-images.githubusercontent.com/57394771/133420355-40f01fe4-baa7-4f8e-afc4-9bcea7b82968.png)

If I just set up time filter to +1 day, it starts working properly.
![image](https://user-images.githubusercontent.com/57394771/133420710-e862bd0f-d8f7-4049-8d99-d8c5f389731a.png)
 
---------------------------------------------------------------------------------------------------------- 

There're cases when it works fine with time filter such as y(yyyy:MM:dd  00:00:00 - yyy:MM:dd hh:mm:ss), but I cannot undestand when and why.

**Comment by dima-altinity** [comment]
@theSaintBelial 
DateTime64 data type was not supported by CH ODBC driver.
Recently this support was added. Try to update CH driver to latest (1.1.10 )

**Comment by dima-altinity** [comment]
I reference to this issue
https://github.com/ClickHouse/clickhouse-odbc/issues/364

**Comment by dima-altinity** [comment]
@theSaintBelial 
I published 1st stable release  (packaged and signed). It contains fix for this problem.
Dont forget to install latest ODBC driver.
