### ISSUE TITLE
JOIN ON with OR conditions to check for NULL values

### ISSUE THREAD

**Issue by griguolcomerranas** [Altinity/clickhouse-tableau-connector-odbc#14]
First of all thanks a lot for the great work with this connector. Many things that failed with the ODBC driver are working great now.

However I still find very frequently these kind of errors:

_HTTP status code: 500 Received error: Code: 403. DB::Exception: Unsupported JOIN ON conditions. Unexpected '(`$temp0` = Calculation_812899764915064837) OR ((`$temp0` IS NULL) AND (Calculation_812899764915064837 IS NULL))': While processing (`$temp0` = Calculation_812899764915064837) OR ((`$temp0` IS NULL) AND (Calculation_812899764915064837 IS NULL)). (INVALID_JOIN_ON_EXPRESSION) (version 21.11.1.8636 (official build)) 
Connector Class: clickhouse_odbc, Version: 0.0.1_

It is basically an OR condition included in the JOIN ON and this is not fully supported in ClickHouse.
My concern is I am not sure the OR condition is really needed. When I face this error the OR condition is always to check if the JOIN keys are NULL.
Is this NULL condition really necessary? Is there any way to configure the connector to avoid those OR...IS NULL conditions?

There are some related issues on clickhouse github ([#22509](https://github.com/ClickHouse/ClickHouse/issues/22509) and [#17612](https://github.com/ClickHouse/ClickHouse/issues/17612))  for additional context.

Thanks again!

**Comment by dima-altinity** [comment]
@griguolcomerranas 
these 2 things ("OR in JOIN" and "JOIN on NULL" ) are not implemented in CH yet and could not be fixed on connector side.

I think that the only way to handle this situation now is find out why Tableau generates such query and try to change it.
Could you  post table structure ( or SELECT query) used as datasource and what type of Tableau calculation you do to have such query.

**Comment by griguolcomerranas** [comment]
Sure, here a sample twb workbook using the demo server from Altinity cloud:
[clickhouse_altinity_demo_issue_join_on_or_null.zip](https://github.com/Altinity/clickhouse-tableau-connector-odbc/files/7503526/clickhouse_altinity_demo_issue_join_on_or_null.zip)

It is a stupid example just to reproduce the issue (Sheet 1).

Basically I do a "FIXED" calculation to to be used later as filter and in other calculations for other sheets.
The generated query has a join on with an or condition checking for null values. I don't think the null checks are very relevant. Perhaps they can be removed somehow.

**Comment by UnamedRus** [comment]
ClickHouse issue about this topic.

https://github.com/ClickHouse/ClickHouse/issues/26928

JOIN OR

https://github.com/ClickHouse/ClickHouse/pull/21320

Some conditions optimizations for JOIN

https://github.com/ClickHouse/ClickHouse/pull/27021

**Comment by yurifal** [comment]
Hi @griguolcomerranas , 
Could you please confirm that the issue still exists 
with the stable (v1.0.0) release of the connector?

**Comment by griguolcomerranas** [comment]
Hi! Everything seems to be working fine with the  new v1.0.0 release of the connector.
This is absolutely great!!!
Thanks a lot for your help!

**Comment by dima-altinity** [comment]
@griguolcomerranas 
would you mind to leave feedback about connector using this form?
https://forms.gle/aiQCKknKr8RfW5Le7

Tableau collects this feedback to publish connector in their gallery.

**Comment by griguolcomerranas** [comment]
> @griguolcomerranas would you mind to leave feedback about connector using this form? https://forms.gle/aiQCKknKr8RfW5Le7
> 
> Tableau collects this feedback to publish connector in their gallery.

Done! And I will make sure some other colleagues leave also their feedback.
Thanks!
