### ISSUE TITLE
"Cannot interpret '130675.19999999792' as double: string consumed partially" in Tableau

### ISSUE THREAD

**Issue by AlejandroJL** [Altinity/clickhouse-tableau-connector-odbc#15]
# Info
SO: MacOS Big Sur
Taleau: 2020.4
OBDC Connector: v1.0.0

# Error
Cannot interpret '130675.19999999792' as double: string consumed partially

# Explanation
When the currency format in the operating system where tableau is running uses decimal separated by the symbol **,** it causes tableau to generate the following error. If we change to American format where decimals are separated by the symbol **.** This does not happen

Thanks!!!

**Comment by dima-altinity** [comment]
unfortunately there is no way to control it in connector. Its managed by regional settings from your OS.
