### ISSUE TITLE
the flows run failed   ---  loomFlowOrchestrationResourceBundle-ConnectToRemoteServerFailureExceptionMsg

### ISSUE THREAD

**Issue by jockeyvv** [Altinity/clickhouse-tableau-connector-odbc#16]
On the floweditor ,it's normal/ but on the task failed.
![2a23d2743a2c28f82d772da6e214d39](https://user-images.githubusercontent.com/24952413/145363058-8ea0b2d5-4245-41e7-8daf-f7463b1b29b1.png)

![a4762b228f45d5ca41ed72ce09e2a80](https://user-images.githubusercontent.com/24952413/145363165-4e8de0dc-f510-4d24-8bc3-0d1adac31626.png)

The output step failure message: loomFlowOrchestrationResourceBundle-ConnectToRemoteServerFailureExceptionMsg com.tableausoftware.server.status.reporting.TableauRuntimeException: loomFlowOrchestrationResourceBundle-ConnectToRemoteServerFailureExceptionMsg

**Comment by dima-altinity** [comment]
I assume that its DataPrep and you installed connector into DataPrep like described here  https://help.tableau.com/current/prep/en-us/prep_connect.htm#custom-connectors

Do you have logs from DataPrep to see exact error?
@jockeyvv

**Comment by jockeyvv** [comment]
> I assume that its DataPrep and you installed connector into DataPrep like described here https://help.tableau.com/current/prep/en-us/prep_connect.htm#custom-connectors
> 
> Do you have logs from DataPrep to see exact error? @jockeyvv

I installed the clickhouse_jdbc.taco into Tableau Prep Builder and  Linux Tableau Server like described here ：https://tableau.github.io/connector-plugin-sdk/docs/run-taco#run-your-under-development-connector

Then the local Tableau Prep Builder works normal，but the flow on the Tableau Server prep floweditor previews normal ，but on the backgrounder task failed，I only found the job log like
“”
The output step failure message: loomFlowOrchestrationResourceBundle-ConnectToRemoteServerFailureExceptionMsg com.tableausoftware.server.status.reporting.TableauRuntimeException: loomFlowOrchestrationResourceBundle-ConnectToRemoteServerFailureExceptionMsg
 “”

**Comment by dima-altinity** [comment]
check Tableau Server logs for detailed error.
Need more detailed information about ConnectToRemoteServerFailureExceptionMsg

**Comment by dima-altinity** [comment]
https://stackoverflow.com/questions/62215385/flow-does-not-run-on-tableau-server-where-can-i-see-the-actual-error
this might be helpful how to get logs
