### ISSUE TITLE
Can we have a clickhouse_odbc.taco with Unicode Driver??

### ISSUE THREAD

**Issue by jockeyvv** [Altinity/clickhouse-tableau-connector-odbc#18]
![image](https://user-images.githubusercontent.com/24952413/147376775-7eea9694-708e-4026-ac8f-58719c1e21bc.png)

Can we have a clickhouse_odbc.taco with Unicode Driver??

![image](https://user-images.githubusercontent.com/24952413/147376827-946448af-b7da-46c9-91d6-e2911c705ad9.png)

Chinese display garbled when I use the default ANSI Driver ，so，Can we have a Unicode Driver version？

**Comment by dima-altinity** [comment]
@jockeyvv 
yes, unicode version was published in releases. Just downlod TACO file

**Comment by kuntzi** [comment]
Hi @dima-altinity,

Could you please recompile ClickHouse Unicode ODBC TACO file, because I opened it as ZIP and found still using ANSI version of driver? It works wrong with Cyrirllics.
