### ISSUE TITLE
MEDIAN function does not work

### ISSUE THREAD

**Issue by griguolcomerranas** [Altinity/clickhouse-tableau-connector-odbc#21]
In latest Unicode connector.
When trying to use MEDIAN function from tableau there is an error:

_Unknown aggregate function MEDIAN. Maybe you meant: ['median']._

When I look into the dialect file I see MEDIAN is defined like this
```
    <function group='aggregate' name='MEDIAN' return-type='real'>
      <formula>MEDIAN(%1)</formula>
      <unagg-formula>%1</unagg-formula>
      <argument type='real' />
    </function>
    <function group='aggregate' name='MEDIAN' return-type='int'>
      <formula>MEDIAN(%1)</formula>
      <unagg-formula>%1</unagg-formula>
      <argument type='int' />
    </function>
```
Looks like "MEDIAN" with uppercase is not recognized correctly by clickhouse.
If I change it to lowercase it works. Like this:
```
    <function group='aggregate' name='MEDIAN' return-type='real'>
      <formula>median(%1)</formula>
      <unagg-formula>%1</unagg-formula>
      <argument type='real' />
    </function>
    <function group='aggregate' name='MEDIAN' return-type='int'>
      <formula>median(%1)</formula>
      <unagg-formula>%1</unagg-formula>
      <argument type='int' />
    </function>
```
Could you please correct it?

Even better, my suggestion would be to use **medianExact**  (alias for quantileExact) for the MEDIAN function. In this way we have 2 choices when working from Tableau:  MEDIAN for quantileExact and PERCENTILE50 for quantile with quicker, approximate values.
I found some complex query calculations where using quantile was ending up in error messages while quantileExact was working fine.

Thanks for your great work!

**Comment by dima-altinity** [comment]
@griguolcomerranas 
thnx for pointing to this typo. Yes, I'm going to fix it and release in next couple days

**Comment by dima-altinity** [comment]
@griguolcomerranas 
it was fixed and published. Could you check?

**Comment by griguolcomerranas** [comment]
Yes! it works great now in the Unicode connector! And I see you are using medianExact, even better :)

The older ANSI version of the connector is still containing the error. No problem for me, I use the Unicode version.

Thanks a lot for your help!!
