### ISSUE TITLE
data type datetime64 shows up as a string in Tableau (using Clikchouse ODBC driver and connector)

### ISSUE THREAD

**Issue by jorgecabrera85** [Altinity/clickhouse-tableau-connector-odbc#3]
![image](https://user-images.githubusercontent.com/86806156/124317829-c8061400-db45-11eb-8a2d-44057897bbc7.png)

**Comment by jorgecabrera85** [comment]
reference to https://github.com/ClickHouse/clickhouse-odbc/issues/364

**Comment by cristianc-ty** [comment]
+1 we also bumped into this issue and worked around it by rewriting the query.

**Comment by dima-altinity** [comment]
new version of  ClickHouse ODBC driver 1.1.10 was released recently that fixed this bug.
Try to update driver and connector to latest. It solves this issue.

**Comment by dima-altinity** [comment]
@joooon 
is this query generated by Tableau or written by you?
can you show structure of your table ? ( fields and their types)

**Comment by joooon** [comment]
The query is produced by Tableau.
These are the relevant statements - apologies for the heavy redaction. Hopefully they will answer your question.
```
clickhouse1 :) describe table a;

DESCRIBE TABLE a

┌─name────────────┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ some_date       │ Date   │              │                    │         │                  │                │
│ some_other_date │ Date   │              │                    │         │                  │                │
...
└─────────────────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```
```
SHOW CREATE TABLE active_devices

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.a
(
    `some_date` Date,
    `some_other_date` Date,
    ...
)
ENGINE = ReplicatedSummingMergeTree('/clickhouse/clusters/.../tables/a', '{replica}')
PARTITION BY toYYYYMM(some_date)
ORDER BY (..., some_other_date, some_date)
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by dima-altinity** [comment]
@joooon 
ok, I see where problem is. 
In next 48hrs I'm going to push fix for that.

**Comment by dima-altinity** [comment]
@joooon 
new version of connector with a lot of fixes was just published.
pls try and check if problem has gone

**Comment by joooon** [comment]
Hi, we have tested the new version of the connector and we're successfully running our queries from both Tableau Desktop and Tableau Server.
Thanks for the quick action!

**Comment by dima-altinity** [comment]
@joooon 
Today connector was published in Tableau Gallery ( check beta section).
I also published it here as release (packaged and signed) so you dont need to have workaround with command line arguments to install it. 
Could you leave your feedback here? ( Tableau collects feedback to move it from beta to main section)
https://forms.gle/aiQCKknKr8RfW5Le7

**Comment by joooon** [comment]
Hi, I've left the feedback for the connector. Thanks again.
