### ISSUE TITLE
Tableau doesn't recognize the data source type "Clickhouse_ODBC"

### ISSUE THREAD

**Issue by jorgecabrera85** [Altinity/clickhouse-tableau-connector-odbc#4]
Hi Folks,

I used the latest version of the "clickhouse-odbc" driver from the link: https://github.com/ClickHouse/clickhouse-odbc/releases. I also used the connector "clickhouse-tableau-connector-odbc" as per the instruction listed out here: https://github.com/Altinity/clickhouse-tableau-connector-odbc. After doing this, I can able to access and visualize clickhouse data using Tableau Desktop.

![image](https://user-images.githubusercontent.com/86806156/124318731-1831a600-db47-11eb-899a-0dec4d242e9d.png)
Problem:

When I try to publish to Tableau Server, I got the following error:

![image](https://user-images.githubusercontent.com/86806156/124318753-2253a480-db47-11eb-924e-41799e6a0a7b.png)

Could you please advice me what the issue is and what I can try to resolve this issue?

Thanks,
JC
please refer to https://github.com/ClickHouse/clickhouse-odbc/issues/362
Both (driver and connector are installed in Tableau server (Linux), as explained in the link provided.

**Comment by cristianc-ty** [comment]
Hey jorgecabrera85,

    I had the same problem, for me the problem was that the connector was not installed on my Tableau Server, when I tried to install it I had some issues hence I opened https://github.com/Altinity/clickhouse-tableau-connector-odbc/issues/2 (since then I found a workaround posted in that link).

All the best,
Cristian

**Comment by dima-altinity** [comment]
Both CH odbc driver and connector should be installed on server.
It seems that connector should be installed as TACO. 
Soon this TACO package will be available in  Tableau Galley.
