### ISSUE TITLE
Linked successfully. But still can not run any query?

### ISSUE THREAD

**Issue by sherrychenzhang** [Altinity/clickhouse-tableau-connector-odbc#6]
![image](https://user-images.githubusercontent.com/26593734/125761887-d24d5273-ad09-4d00-bd62-119524307d2a.png)

**Comment by dima-altinity** [comment]
@sherrychenzhang 
can you try to update driver and connector to latest?
and  share full text of our SELECT query?

**Comment by dima-altinity** [comment]
New connector was published in Tableau Gallery  with a lot of fixes.
Pls try - it should fix your problem.
