### ISSUE TITLE
FETCH SIZE

### ISSUE THREAD

**Issue by theSaintBelial** [Altinity/clickhouse-tableau-connector-odbc#7]
Hi, Altinity, nice connector!

But there is a question. I work with quite a big datasets and I know that other odbc drivers supports its configuring to optimize queries and improve efficiency. 

Is it possible to configure odbc connection using by your connector? For example, change fetch size, etc.

Thx

**Comment by traceon** [comment]
Can be related to `CAP_ODBC_FETCH_BUFFERS_SIZE_MASSIVE` Tableau capability.

**Comment by theSaintBelial** [comment]
> Can be related to `CAP_ODBC_FETCH_BUFFERS_SIZE_MASSIVE` Tableau capability.

Thx 👍 )
