### ISSUE TITLE
While publish the report from tableau desktop to tableau server using Tableau Connector for ClickHouse facing connectivity issue 

### ISSUE THREAD

**Issue by ananthdevulapalli** [Altinity/clickhouse-tableau-connector-odbc#9]
Hi Team,

I am facing an issue while publishing a report from tableau desktop to the tableau server using tableau connector for clickhouse 

below is the screen shot for reference

![clickhouse_publish](https://user-images.githubusercontent.com/29634893/129516614-0b0d612c-962d-4698-a89d-a015ae97c84e.PNG)

we are using cloud hosted tableau server for connectivity from tableau desktop

**Comment by dima-altinity** [comment]
Both CH odbc driver and connector should be installed on Tableau Server.
It seems that connector should be installed as TACO.
Soon this TACO package will be available in Tableau Galley.
